owner: Hans5958
repo: VocaDB-Upptime

sites:
  - name: VocaDB
    url: https://vocadb.net
  - name: UtaiteDB
    url: https://utaitedb.net
  - name: TouhouDB
    url: https://touhoudb.com

status-website:
  # cname: demo.upptime.js.org
  baseUrl: /VocaDB-Upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: Welcome to the unofficial Upptime status page for **[VocaDB](https://scratch.mit.edu)**.
  introMessage: This is the status page for [VocaDB](https://vocadb.net) and other adjacent services, provided by [Hans5958](https://hans5958.github.io). It monitors them for free using GitHub services, thanks to [Upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
user-agent: Auto5958
commitMessages:
  commitAuthorName: Auto5958
  commitAuthorEmail: 69833949+Auto5958@users.noreply.github.com
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
